language: node_js
node_js:
- 'stable'
cache:
directories:
- 'node_modules'
before_install: cd ./api
install:
- npm install
before_script:
- psql -c 'create database testdb;' -U postgres
script:
- npm run coverage