export default {
  users: [
    {
      id: 1,
      email: 'first@email.com',
      firstName: 'Yoshi',
      lastName: 'Yama',
      password: 'password',
      type: 'client',
      isAdmin: false,
    },
    {
      id: 2,
      email: 'second@email.com',
      firstName: 'Yetunde',
      lastName: 'George',
      password: 'password',
      type: 'staff',
      isAdmin: false,
    },
    {
      id: 3,
      email: 'third@email.com',
      firstName: 'Faith',
      lastName: 'Praise',
      password: 'password',
      type: 'client',
      isAdmin: false,
    },
    {
      id: 4,
      email: 'fourth@email.com',
      firstName: 'Naruto',
      lastName: 'Uzumaki',
      password: 'password',
      type: 'staff',
      isAdmin: true,
    },
  ],
};
